[IV-23-24] Objetivo 0
PabloBarTo/Empresa pull request #1
Opened 2023-09-19 18:33 UTC by PabloBarTo

2023-09-20 12:21 UTC, JJ requested changes
Gracias por enviarlo. Me temo que todavía tienes que avanzar un poco más para conseguir el objetivo. De [los errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md):

> Expresar el problema como "la persona quiere o desea". Esto será, en todo caso, una expresión de una posible solución a un problema (que puede tener otras muchas y que, en todo caso, es algo que hay que explorar durante el desarrollo). Un problema será, en todo caso, lo que causa que esa persona quiera hacer esa actividad (o cualquier otra que pueda resolverle el problema).

Adicionalmente, como [indica el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio), en el apartado que habla de soluciones no adecuadas, que serían las que incluyen

> “buscar”, “dar de alta”, “poner en contacto”, “recuperar”, “integrar”, “alertar”, “comunicar”.

O, en general, los que almacenan y recuperan información y, por tanto, no tienen lógica de negocio suficiente.

En el mismo guión menciona la metodología de "design thinking" para poder, a través de la fase de empatización, precisar y formular los problemas que se van a llevar a cabo. Te animaría a que la usaras con tu padre, para ver si se puede llegar a algún problema que se pueda usar en la asignatura.

A través de un juego de rol, también la llevaremos a cabo en clase, también en la siguiente clase, mañana. Te animo a que te acerques a clase para que sea más fácil aplicar esta metodología para superar el objetivo 0.

2023-09-20 14:12 UTC, PabloBarTo commented
@

2023-09-20 15:42 UTC, JJ requested changes
Te rogaría que [consultaras de nuevo los errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md), entre los que está:

> Hablar desde el principio de "Quiero hacer una aplicación que haga..." cuando lo que se pide es que se describa un problema.

En este caso "ayudar con las facturas". Por otro lado, también : 
> Crear problemas demasiado vagos ("una persona quiere invertir") o simplemente descritos como tales ("el problema del transporte").

En general, convendría que trataras de entender qué se requiere de este objetivo y por qué. Al final, es la descripción de un problema que pueda servir al menos para empezar a trabajar en una aplicación.

2023-09-20 15:42 UTC, JJ commented on README.md
> +Soy un hijo que quiere ayudar a su padre con las facturas de su empresa de fontanería debido a la elevada carga de trabajo y el poco timepo del que dispone para poder realizarlas.
Corrige los errores de tecleo.

2023-09-20 21:04 UTC, PabloBarTo commented
@JJ Actualizado

2023-09-21 05:35 UTC, JJ requested changes
En la siguiente iteración, te rogaría que añadieras en el README cómo has seguido el proceso de design thinking para poder precisar el problema. Una vez más, ese es el contenido de este objetivo.

2023-09-21 05:35 UTC, JJ commented on README.md
> +La liga española de fútbol quiere regular el dinero que invierte cada equipo en salarios y presupuesto de fichajes ya que quieren evitar que los equipos paguen por encima de sus posibilidades durante
No entiendo muy bien. ¿Cuál es el problema?

2023-09-21 06:42 UTC, PabloBarTo commented on README.md
> +La liga española de fútbol quiere regular el dinero que invierte cada equipo en salarios y presupuesto de fichajes ya que quieren evitar que los equipos paguen por encima de sus posibilidades durante
El problema es que hay varios equipos que se suelen pasar de ese límite y tienen problemas para pagar a sus jugadores y por tanto la liga quiere regular en que invierte el dinero cada club para que eso no ocurra.

2023-09-21 07:23 UTC, PabloBarTo commented
@JJ Actualizado

2023-09-21 11:24 UTC, JJ requested changes
Está bien que apliques lo que hemos hablado, pero mejor todavía que lo hagas con detalles como si no lo hubiéramos hablado. Al final, el problema hay que describirlo bien si o si.

2023-09-21 11:24 UTC, JJ commented on README.md
> +Soy un jugador de la liga fantasy y cada semana no sé qué jugadores debo comprar para ganar a mis amigos en puntos.
Imagínate que esto lo está corrigiendo un profesor con el que no has hablado y que además no tiene ni idea de lo que es la Liga Fantasy. Por favor, especifica un poco mejor las cosas.

2023-09-21 12:36 UTC, PabloBarTo commented
@JJ Actualizado

2023-09-21 12:39 UTC, JJ approved these changes
:+1: Lo voy a dar por aprobado, pero sin decir nada del presupuesto, en principio no existe el problema. Por favor, acláralo antes de fusionarlo y trata en el futuro de ser más cuidadoso y tener más atención al detalle.

2023-09-21 12:39 UTC, JJ commented on README.md
> +Soy un jugador de la liga fantasy que es un juego en el que tienes que formar una plantilla con once jugadores que obtienen su puntación en función del partido, es decir, de lo bien o mal que jueguen
¿Con un presupuesto ilimitado? ¿Limitado? ¿De qué depende el presupuesto?

2023-09-22 07:21 UTC, merged