Subida de objetivo
PabloBarTo/Empresa pull request #2
Opened 2023-09-25 09:20 UTC by PabloBarTo

2023-09-25 13:34 UTC, Morad02 commented on docs/milestones
> +Métodos y código que hay que desarrollar para implementar el algoritmo, que teniendo en cuenta el presupuesto del que disponemos y la información de los jugadores analizada anteriormente nos informe
"Métodos" tampoco es un producto

2023-09-25 13:37 UTC, Morad02 commented
La HU creo que está bien. Revisa todos los milestones teniendo en cuenta lo que te he comentado.  Cuando lo corrijas me avisas. Suerte!

2023-09-25 20:35 UTC, PabloBarTo commented
@Morad02 Actualizado con lo que me has comentado

2023-09-26 14:05 UTC, Morad02 commented on docs/milestones
> +
Aquí pasa lo mismo.  Cuando dices que va a devolver un informe te refieres a la solución y no al PMV

2023-09-26 14:06 UTC, Morad02 commented on docs/milestones
> +Código y clases que hay que desarrollar para implementar el algoritmo, que teniendo en cuenta el presupuesto del que disponemos y la información de los jugadores analizada anteriormente nos informe c
Ponle un título que refleje cuál va a ser el producto y no uno genérico

2023-09-26 14:08 UTC, Morad02 commented
Te aconsejo que vuelvas a leer el guión y los materiales del profesor para aclararte sobre los PMVs. Además, intenta añadir más contexto a la historia de usuario para que pueda servir de partida para poder hacer un modelo del problema. Cuando lo corrijas me avisas. Suerte!

2023-09-26 16:54 UTC, PabloBarTo commented
@Morad02 Actualizado de nuevo

2023-09-26 17:47 UTC, PabloBarTo commented
@Morad02 He hecho un cambio de lo que había subido anteriormente

2023-09-26 17:48 UTC, Morad02 approved these changes
Creo que está listo para que lo revise el profesor. Suerte!

2023-09-26 17:49 UTC, PabloBarTo commented
Gracias

2023-09-26 17:49 UTC, PabloBarTo commented
@JJ

2023-09-26 18:25 UTC, JJ requested changes
Os sugiero que comentéis en privado el contexto y demás, y penséis entre los dos qué problemas pueden ser los más interesantes. Si es necesario, darle una vuelta al juego de rol para ver qué podéis sacar en claro. También puede ser que los datos de la liga fantástica estén en una página web semiestructurada y sea no trivial procesarlos, o que vayáis a usar datos de otras páginas para obtener datos y usarlos en la Liga Fantástica, no lo sé. En todo caso, os rogaría que reorientárais algo el problema original y por tanto las HUs para poder sacar adelante este objetivo.
En todo caso, agradezco a @Morad02 el trabajo, que creo que ha sido acertado, y ha ayudado a mejorar.

2023-09-26 18:25 UTC, JJ commented on docs/historias_de_usuarios
> +[HU1] Voy último en un juego, que es la liga fantasy, que es un juego que estoy jugando con mis amigos, en el que formas una plantilla con once jugadores y estos jugadores obtienen puntos en función
Tienes un problema similar a @javigp2002 [aquí](https://github.com/javigp2002/LazyFood/pull/2). No tienes suficientes detalles para poder desarrollar el producto. Pero es que cuantos más detalles hemos ido viendo (él lo ha desarrollado en un *user journey*), más complicado he visto el problema (o más simple, que es lo mismo).

Voy a intentar resumir.

1. Si el problema es que *cada jornada* o *al principio de la temporada* hay que fichar exactamente 11 jugadores (ni uno más ni uno menos) con 100 millones de euros, podría ser un problema interesante, pero dependerá de cómo estén organizadas las puntuaciones de los jugadores (que por lo que he entendido, son más o menos las mismas que el precio).
2. Si no es así, el reto es que lo que resuelve el problema sería contratar los jugadores que van a tener más puntuación para el precio que tienen *en el futuro*. Eso es un problema de predicción, **que no se puede abordar en la asignatura**.

Lo que le he sugerido al compañero es que piense en aspectos específicos (seleccionar un jugador para vender, optimizar la cláusula de rescisión de un jugador dependiendo de datos sobre el mismo, seleccionar el jugador más parecido a uno determinado a la hora de sustituir un jugador por otro en función de una serie de parámetros).

En todo caso, tanto @javigp2002 como tú tendréis que darle un par de vueltas para poder, a partir del contexto, que es el mismo, encontrar una serie de problemas específicos/historias de usuario, que si puede ser sean diferentes para cada uno.

2023-09-27 13:10 UTC, PabloBarTo commented
@JJ Actualizado

2023-09-27 15:34 UTC, JJ requested changes
No sé dónde has hecho los cambios; no donde se te ha señalado.

2023-09-27 15:34 UTC, JJ commented on docs/milestones
> +La intención es definir el modelo del problema que presenta el usuario y las partes clave a partir de los HUs y obtener el código modularizado del modelo del problema. Será viable si lo aprueba el pr
los modelos no se definen, se construyen. "Definición" parece que lo haces de la nada, o que el modelo ya está ahí.

2023-09-27 18:52 UTC, PabloBarTo commented
@JJ Actualizado de nuevo

2023-09-28 10:34 UTC, JJ requested changes
Hay algunos cambios que son de detalle, pero sí es importante que toda HU tenga claramente identificado el cliente de que se trata.

2023-09-28 10:34 UTC, JJ commented on docs/historias_de_usuarios
> +[HU2] Quiero saber que sería más rentable para mi plantilla, es decir la opción que sea mejor tanto económicamente como en cantidad de puntos, si comprar un jugador de los que queda en el mercado o c
¿Es el mismo cliente que la HU primera? Las HUs siempre tienen que tener un cliente. Si es necesario y hay diferentes roles, hay que usar la metodología de *personas* para describirlos (como hemos hecho en el hackatón)

2023-09-28 10:34 UTC, JJ commented on docs/milestones
> +
Si lo has resuelto cambiándo otra línea, indícalo así "REsuelto en *número de commit*". También, como esto está comentado una línea en blanco, puedes simplemente borrarla.

2023-09-28 10:34 UTC, JJ commented on docs/milestones
> +La intención es costruir el modelo del problema que presenta el usuario y las partes clave a partir de los HUs y obtener el código modularizado del modelo del problema. Será viable si lo aprueba el p
typo: costruir.

2023-09-28 18:52 UTC, PabloBarTo commented
@JJ Listo para revisión

2023-09-29 05:40 UTC, JJ reviewed
Tienes que resolver todos los comentarios. Sigue habiendo tres comentarios de @Morad02 sin resolver.

2023-09-29 07:25 UTC, PabloBarTo commented
@JJ Comentarios resueltos

2023-09-29 07:36 UTC, JJ approved these changes
👍 
Por favor, cuando resuelvas los comentarios trata de poner por qué se han resuelto.

2023-09-29 08:02 UTC, merged