[IV-23-24] Objetivo4
PabloBarTo/Empresa pull request #23
Opened 2023-11-21 14:53 UTC by PabloBarTo

Se ha eliminado un espacio en blanco que había en el archivo

2023-11-22 18:48 UTC, manuelvico0102 requested changes
Hay algunos commit que no siguen las buenas prácticas, ya que no hacen referencia a algunos issue. Aparte de las cosas que te he comentado, creo que lo demás está bien.

2023-11-22 18:48 UTC, manuelvico0102 commented on docs/elección_test_runner.md
> +- También debe tener un buen mantenimiento, es decir que si hay errores o cualquier problema lo vayan solucionando con cualquier actualización.
Este criterio creo que sería necesario expresarlo mejor, porque es complicado ver cual tiene un buen mantenimiento ya que no hay una manera simple de cuantificarlo. Otra cosa es si tu criterio fuese que los test runner tengan mantenimiento y no estén inactivos.

2023-11-22 18:48 UTC, manuelvico0102 commented on docs/elección_test_runner.md
> +##Selección
Aquí tienes un fallo, supongo que habrá sido al escribirlo rápido. Sería ## Selección

2023-11-22 18:48 UTC, manuelvico0102 commented on docs/elección_test_runner.md
> +# Elección test runner
Aparte de elegir un test runner, también hay que elegir una biblioteca de aserciones y un CLI. Aunque en tu caso hayas elegido Deno test y por consiguiente puedas usar la librería de aserciones por defecto estaría bien que lo explicases e investigases unas cuántas librerías más.

2023-11-22 18:48 UTC, manuelvico0102 commented on deno.json
> +        "test": "deno test --allow-read test/comprobacion.ts"
No he usado deno test, pero viendo los repositorios de otros compañeros que lo han usado creo que no es necesario indicar el archivo de test

2023-11-23 08:52 UTC, PabloBarTo commented
@manuelvico0102 Listo para revisión de nuevo. 😎

2023-11-23 08:56 UTC, PabloBarTo commented on deno.json
> +        "test": "deno test --allow-read test/comprobacion.ts"
Resuelto en [8335ff7](https://github.com/PabloBarTo/Empresa/pull/23/commits/8335ff7f4512b30ba163e994c35c96b8292c7922)

2023-11-23 08:56 UTC, manuelvico0102 approved these changes
Yo creo que ya esta listo, pero te faltaría indicar que commits resuelven las sugerencias que te he indicado, en vez de solo cerrarlos

2023-11-23 08:57 UTC, PabloBarTo commented on docs/elección_test_runner.md
> +# Elección test runner
Resuelto en [a079e43](https://github.com/PabloBarTo/Empresa/pull/23/commits/a079e435419b5dc7a4e09220ef7e686ef5a6ddf0)

2023-11-23 08:57 UTC, PabloBarTo commented on docs/elección_test_runner.md
> +##Selección
Resuelto en [a079e43](https://github.com/PabloBarTo/Empresa/pull/23/commits/a079e435419b5dc7a4e09220ef7e686ef5a6ddf0)

2023-11-23 08:57 UTC, PabloBarTo commented on docs/elección_test_runner.md
> +- También debe tener un buen mantenimiento, es decir que si hay errores o cualquier problema lo vayan solucionando con cualquier actualización.
Resuelto en [a079e43](https://github.com/PabloBarTo/Empresa/pull/23/commits/a079e435419b5dc7a4e09220ef7e686ef5a6ddf0)

2023-11-23 08:58 UTC, PabloBarTo commented
Muchas gracias, se me había pasado lo de los commits. Ya está añadido.

2023-11-23 08:59 UTC, PabloBarTo commented
@JJ Listo para revisión.

2023-11-24 06:22 UTC, JJ requested changes
El mayor problema es la presencia de package.json, pero el resto tiene también pequeños problemas. ¿Está en el fichero de tareas el test runner?

2023-11-24 06:22 UTC, JJ commented on package.json
> +  "dependencies": {
Si usas deno no necesitas esto.

2023-11-24 06:22 UTC, JJ commented on src/equipo.ts
>      getNombre(): string {
La mejor práctica para declarar getters es usando la palabra clave `get`

2023-11-24 06:22 UTC, JJ commented on src/equipo.ts
> +        const resultado = this.mercado.seleccionarJugadoresMaxPuntos(this.presupuesto);
Esta redirección de una clase a otra lo que está diciendo es que esta función no debería estar en esta clase. Lo único que está usando de esta clase es el presupuesto, y podía ser perfectamente un argumento de una función.

2023-11-24 06:22 UTC, JJ commented on src/mercado.ts
> +        const buscarCombinacion = (actual: number, seleccion: Jugador[], presupuestoRestante: number): void => {
Uf, esta forma de declarar una función... ¿por qué no usas la habitual?

2023-11-24 06:22 UTC, JJ commented on test/comprobacion.ts
> +import { assertEquals, assert } from "https://deno.land/std@0.207.0/assert/mod.ts";
En los nombres de ficheros de test también hay buenas prácticas. "comprobacion" es igual que "test". Para encontrarlos, lo más sencillo es que los llames con el nombre de las clases que comprueban + _test o algo así.

2023-11-24 07:54 UTC, PabloBarTo commented on package.json
> +  "dependencies": {
Resuelto en [14177b3](https://github.com/PabloBarTo/Empresa/pull/23/commits/14177b38cab4df279cd0f522b63f4a3b956ab4f3)

2023-11-24 08:02 UTC, PabloBarTo commented on src/equipo.ts
>      getNombre(): string {
Resuelto en [8a98ca9](https://github.com/PabloBarTo/Empresa/pull/23/commits/8a98ca927465d6e9a86d072755ef9b7b50d0ab16)

2023-11-24 08:10 UTC, PabloBarTo commented on test/comprobacion.ts
> +import { assertEquals, assert } from "https://deno.land/std@0.207.0/assert/mod.ts";
Resuelto en [5359d3d](https://github.com/PabloBarTo/Empresa/pull/23/commits/5359d3d260ae5ca64718a1528cedcac0c83ae269)

2023-11-24 09:22 UTC, PabloBarTo commented on src/mercado.ts
> +        const buscarCombinacion = (actual: number, seleccion: Jugador[], presupuestoRestante: number): void => {
Resuelto en [f73a85f](https://github.com/PabloBarTo/Empresa/pull/23/commits/f73a85f988530fd2f3045decb27975b0f8eada5e)

2023-11-24 09:30 UTC, PabloBarTo commented
@JJ Listo para revisión

2023-11-24 10:23 UTC, JJ approved these changes
No voy a bloquear por los getters sin usar, pero por favor asegúrate de que lo que declaras es lo que usas y no "lo pones ahí porque se vaya a usar en el futuro"

2023-11-24 10:23 UTC, JJ commented on src/equipo.ts
> +    get _presupuesto(){
Esto no lo estás usando en ningún otro sitio. ¿Seguro que lo necesitas?

2023-11-24 10:23 UTC, JJ commented on src/equipo.ts
> +    get _jugadores(){
Tampoco veo que esto se use en ningún sitio. ¿Seguro que lo necesitas? ¿Para qué HU?

2023-11-24 11:22 UTC, PabloBarTo commented on src/equipo.ts
> +    get _presupuesto(){
Resuelto en [26e5b88](https://github.com/PabloBarTo/Empresa/pull/23/commits/26e5b88ad662e7cfbb70beffc32111d36d6e1842)

2023-11-24 11:23 UTC, PabloBarTo commented on src/equipo.ts
> +    get _jugadores(){
Resuelto en [26e5b88](https://github.com/PabloBarTo/Empresa/pull/23/commits/26e5b88ad662e7cfbb70beffc32111d36d6e1842)

2023-11-24 11:23 UTC, merged