[IV-23-24] Objetivo 5
PabloBarTo/Empresa pull request #25
Opened 2023-11-26 12:28 UTC by PabloBarTo

* [x] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?
* [x] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?
* [x] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [x] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
vez, se va a usar cientos o miles de veces)
* [x] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [x] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?
* [x] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [x] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [x] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [x] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [x] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?
* [x] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [x] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?
* [x] ¿Se ha abierto un shell en el contenedor una vez construida la imagen y
comprobado que los ficheros que se necesitan están todos incluidos, y que no hay
ficheros que no se necesiten?

2023-11-28 09:45 UTC, javigp2002 reviewed
En general los archivos de configuración están bien, sin embargo, a la hora de elegir me parece que has resumido demasiado. Buen trabajo igualmente 😄

2023-11-28 09:45 UTC, javigp2002 commented on docs/eleccion_imagen.md
> +- La imagen que seleccionemos debe ser compatible con deno.
Si quieres que sea compatible con deno debes especificar cuales son y porqué son esas, es decir, donde has encontrado la información

2023-11-28 09:45 UTC, javigp2002 commented on docs/eleccion_imagen.md
> +- También buscaremos que la imagen sea lo más ligera posible ya que eso ayudará en los tiempos de ejecución.
No tengo claro porque una imagen ligera ayuda en los tiempos de ejecución.

2023-11-28 09:45 UTC, javigp2002 commented on docs/eleccion_imagen.md
> +Siguiendo los criterios definidos previamente nos enfocaremos en la imagen que trae deno instalado. Dentro de esta opción podemos elegir entre los siguientes SO.
Los criterios sobre que tenga deno instalado está bien pero si vas a poner el nombre de solo los SO deberías añadir los links de las imágenes para conocer cuales son estas

2023-11-28 09:45 UTC, javigp2002 commented on docs/eleccion_imagen.md
> +Debian tiene un tamaño de 28.74 MB.
En todas comentas la importancia del tamaño y solo eso.

2023-11-28 09:45 UTC, javigp2002 commented on docs/eleccion_imagen.md
> +Siguiendo la información dada en snyk Advisor los dos mejores valorados son Ubuntu y Alpine. Por tanto teniendo en cuenta esta valoración y los tamaños de cada uno nos quedaremos con Alpine, ya que e
Es la primera vez que mencionas a snyk y es en la selección. Si es un punto importante para la elección deberías mencionarlo previamente y en cada uno de los candidatos puesto que, sino, el que lo lea se está "fiando" de ti.

2023-11-28 10:36 UTC, PabloBarTo commented on docs/eleccion_imagen.md
> +- La imagen que seleccionemos debe ser compatible con deno.
Resuelto en [c0b8eb1](https://github.com/PabloBarTo/Empresa/pull/25/commits/c0b8eb17010bd032244feee82cd55709c1c5f858)

2023-11-28 10:36 UTC, PabloBarTo commented on docs/eleccion_imagen.md
> +- También buscaremos que la imagen sea lo más ligera posible ya que eso ayudará en los tiempos de ejecución.
Resuelto en [c0b8eb1](https://github.com/PabloBarTo/Empresa/pull/25/commits/c0b8eb17010bd032244feee82cd55709c1c5f858)

2023-11-28 10:36 UTC, PabloBarTo commented on docs/eleccion_imagen.md
> +Debian tiene un tamaño de 28.74 MB.
Resuelto en [c0b8eb1](https://github.com/PabloBarTo/Empresa/pull/25/commits/c0b8eb17010bd032244feee82cd55709c1c5f858)

2023-11-28 10:36 UTC, PabloBarTo commented on docs/eleccion_imagen.md
> +Siguiendo la información dada en snyk Advisor los dos mejores valorados son Ubuntu y Alpine. Por tanto teniendo en cuenta esta valoración y los tamaños de cada uno nos quedaremos con Alpine, ya que e
Resuelto en [c0b8eb1](https://github.com/PabloBarTo/Empresa/pull/25/commits/c0b8eb17010bd032244feee82cd55709c1c5f858)

2023-11-28 10:38 UTC, PabloBarTo commented
Muchas gracias @javigp2002 por la revisión! He arreglado lo que me has sugerido. Cualquier otra cosa que consideres que deba modificar me avisas.

2023-11-28 11:10 UTC, javigp2002 reviewed
Creo que falta un poco, a mi parecer. Pero buen trabajo de nuevo, mira la review y me cuentas 😄

2023-11-28 11:10 UTC, javigp2002 commented on docs/eleccion_imagen.md
> +- También buscaremos que la imagen sea lo más ligera posible ya que hará que tengamos que cargar menos datos cada vez que iniciemos el contenedor.
Creo recordar que la rapidez con la que se inicia el contenedor no es un problema para este objetivo. Mira los requisitos del mismo.

2023-11-28 11:10 UTC, javigp2002 commented on docs/eleccion_imagen.md
> +[Alpine](https://hub.docker.com/_/alpine)
Pero aunque estas sean las imágenes en docker, realmente, también es importante las imágenes que vas a escoger dentro de deno puesto que " previamente nos enfocaremos en la imagen que trae deno instalado". Por tanto estos no son los que debes evaluar, creo...

2023-11-28 11:10 UTC, javigp2002 commented on docs/eleccion_imagen.md
>  # Debian
Los links suele ser más útil de cara a cuando alguien esté leyendo el archivo tenga acceso rápido a los mismos y no tenga que subir.

2023-11-28 11:40 UTC, PabloBarTo commented on docs/eleccion_imagen.md
>  # Debian
Resuelto en [232265c](https://github.com/PabloBarTo/Empresa/pull/25/commits/232265cf9b05e023d58fdc80e49e7c1d11e1a19a)

2023-11-28 11:41 UTC, PabloBarTo commented on docs/eleccion_imagen.md
> +- También buscaremos que la imagen sea lo más ligera posible ya que hará que tengamos que cargar menos datos cada vez que iniciemos el contenedor.
Resuelto en [232265c](https://github.com/PabloBarTo/Empresa/pull/25/commits/232265cf9b05e023d58fdc80e49e7c1d11e1a19a)

2023-11-28 11:42 UTC, PabloBarTo commented
@javigp2002 cambios realizados de nuevo. Si sigue habiendo cualquier cosas que creas que hay que cambiar me lo comentas sin problema.

2023-11-29 09:16 UTC, PabloBarTo commented on docs/eleccion_imagen.md
> +- También buscaremos que la imagen sea lo más ligera posible ya que eso significará que no requerirá de muchas herramientas para su funcionamiento.
Resuelto en [d673cd7](https://github.com/PabloBarTo/Empresa/pull/25/commits/d673cd7e0cba08956bbb955aaece9d2a4bb8203b)

2023-11-29 09:22 UTC, PabloBarTo commented
Muchas gracias por la revisión! 😁

2023-11-29 09:32 UTC, JJ requested changes
Muchas gracias a @javigp2002 por la revisión. Porfa, dale otra pequeña vuelta.

2023-11-29 09:32 UTC, JJ commented on dockerfile
> +COPY deno.json deno.lock ./
¿Por qué necesitas esto ahora mismo?

2023-11-29 09:32 UTC, JJ commented on dockerfile
> +RUN deno cache --lock=deno.lock deno.json
¿Qué hace esto exactamente ahora?

2023-11-29 09:32 UTC, JJ commented on docs/eleccion_imagen.md
> +Siguiendo la información dada en snyk Advisor los dos mejores valorados son Ubuntu y Alpine. Por tanto teniendo en cuenta esta valoración y los tamaños de cada uno nos quedaremos con Alpine, ya que e
El problema es que snyk solo examina las imágenes oficiales.

2023-11-29 09:32 UTC, JJ commented on docs/eleccion_imagen.md
> +La información sobre qué imágenes son compatibles con deno las he encontrado en [Imágenes compatibles con deno](https://hub.docker.com/r/denoland/deno)
¿Seguro que no hay otras imágenes que pueden ser posibles candidatos?

2023-11-29 09:56 UTC, PabloBarTo commented on dockerfile
> +COPY deno.json deno.lock ./
Para copiar los archivos de configuración de deno que tengo en mi carpeta local al contenedor de docker

2023-11-29 10:00 UTC, PabloBarTo commented on dockerfile
> +RUN deno cache --lock=deno.lock deno.json
Se encarga de comprobar durante la construcción de la imagen que las dependencias que están especificadas en esos archivos están disponibles y que se está usando las versiones correctas

2023-11-29 10:10 UTC, JJ commented on dockerfile
> +COPY deno.json deno.lock ./
¿Qué hay en esos archivos de configuración que necesites dentro del contenedor?

2023-11-29 10:10 UTC, JJ commented on dockerfile
> +RUN deno cache --lock=deno.lock deno.json
¿Y qué dependencias hay ahora mismo?

2023-11-29 10:12 UTC, JJ commented
Dicho de otra forma, ¿has probado a quitar esas dos líneas a ver qué pasa?

2023-11-29 10:26 UTC, PabloBarTo commented
Sí, si lo quito sigue funcionando, solo que Deno gestiona las dependencias en tiempo de ejecución en lugar de en la construcción

2023-11-29 10:27 UTC, PabloBarTo commented on docs/eleccion_imagen.md
> +La información sobre qué imágenes son compatibles con deno las he encontrado en [Imágenes compatibles con deno](https://hub.docker.com/r/denoland/deno)
Resuelto en [b5f041e](https://github.com/PabloBarTo/Empresa/pull/25/commits/b5f041e1c2c4154e083b7ed92eed554730b2f714)

2023-11-29 10:35 UTC, JJ requested changes
Me temo que no hay mucha mejora con respecto a la anterior versión. No has resuelto tampoco los issues.

2023-11-29 10:35 UTC, JJ commented on docs/eleccion_imagen.md
> +Las imágenes que son compatibles con deno y están publicadas en Dockerhub son [Imágenes compatibles con deno](https://hub.docker.com/r/denoland/deno)
No, esas son las imágenes oficiales. Hay bastantes más que son compatibles con deno o incluyen deno. Deberías tenerlas en cuenta.

2023-11-29 11:39 UTC, PabloBarTo commented on docs/eleccion_imagen.md
> +Las imágenes que son compatibles con deno y están publicadas en Dockerhub son [Imágenes compatibles con deno](https://hub.docker.com/r/denoland/deno)
Resuelto en [5c7e55c](https://github.com/PabloBarTo/Empresa/pull/25/commits/5c7e55ceb9b76f399bc2ca9478ed55e8caba9c39)

2023-11-29 11:40 UTC, PabloBarTo commented
https://github.com/PabloBarTo/Empresa/pull/25#issuecomment-1831631024 miraría en lo que hay en /app/test

2023-11-29 12:47 UTC, JJ requested changes
No has resuelto en realidad el comentario. Si esas dos órdenes hacen algo, las dejas (pero abre un issue que indique qué es lo que ocurre si no las pones). Si no hacen nada, es mejor que las borres.

2023-11-29 12:47 UTC, JJ commented on dockerfile
> +COPY deno.json deno.lock ./
No lo has resuelto, Pablo. No lo marques como resuelto. No me has contestado a esa pregunta, y tú mismo me has dicho que funciona sin ellos. Si funciona sin ellos, no los necesita. Y si no los necesita, tampoco el de abajo.

2023-11-29 14:00 UTC, PabloBarTo commented on dockerfile
> +COPY deno.json deno.lock ./
Resuelto en [00ae8bb](https://github.com/PabloBarTo/Empresa/pull/25/commits/00ae8bb1e089a9db04c7802972fa8a4a2ebbf3b3)

2023-11-29 14:03 UTC, JJ approved these changes
:+1:

2023-11-30 07:59 UTC, merged