[IV-23-24] Objetivo 2
PabloBarTo/Empresa pull request #7
Opened 2023-10-23 18:26 UTC by diagmatrix

### Sobre la estructura del repositorio

* [ ] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y
   disposición de los mismos?
* [ ] ¿He mirado tanto reglas generales (para cualquier repo) como reglas
específicas para el lenguaje con el que se está trabajando?

### Sobre el planteamiento

* [ ] ¿Se han planteado una serie de issues, asignados a las historias de
usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e
identifiquen las diferentes partes del problema?
* [ ] ¿Los issues representan un problema, y no una tarea?

### Sobre el análisis del problema

* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [ ] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

### Sobre el código

* [ ] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [ ] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [ ] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [ ] ¿Todos los issues creados están relacionados con a una HU?
* [ ] ¿Ha asignado el propietario/la propietaria del repositorio todos los
issues planteados al *milestone* correspondiente?
* [ ] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [ ] ¿Es el milestone sobre el que estoy trabajando un producto
   mínimamente viable? ¿O tengo que solicitar al product manager que precise de
   qué producto se trata?
* [ ] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2023-10-25 16:58 UTC, diagmatrix commented
@PabloBarTo Puedes revisar el trabajo ya. Asigna los issues que he creado y este PR a #6 cuando puedas.

2023-11-09 15:48 UTC, diagmatrix commented
@PabloBarTo He hecho la modificación de la posición de los jugadores

2023-11-10 08:03 UTC, PabloBarTo requested changes
@diagmatrix ahora sí me convence la estructura de la plantilla y el jugador pero creo que faltaría otra clase para ver los jugadores que hay en el mercado o los jugadores que están disponibles

2023-11-13 17:23 UTC, diagmatrix commented
> @diagmatrix ahora sí me convence la estructura de la plantilla y el jugador pero creo que faltaría otra clase para ver los jugadores que hay en el mercado o los jugadores que están disponibles

Hecho :)

2023-11-13 19:24 UTC, PabloBarTo approved these changes
Por mi parte lo veo todo correcto buen trabajo :smile:  Pongo los check y menciono al profesor para que lo revise,

2023-11-13 19:25 UTC, PabloBarTo commented
- [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y evidencian comprensión de las historias de usuario? Si no es así, es mejor que se le transmita antes de que empiece a crear cualquier código erróneo.

 

- [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido su lista de comprobación?

 

- [ ] ¿El código creado es una modelización válida de las historias de usuario creadas por ti, y te sirve como base para programar la lógica de negocio?

 

- [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de programación que hayáis consensuado, tanto en identificadores, como nombres de ficheros, como disposición de los diferentes ficheros en el repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y aportan código para resolver el problema planteado en el mismo?

- [ ]  ¿He comprobado que el código compile, o que quien lo ha programado ha lo ha hecho y documentado en el repositorio?

 

- [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone correspondiente, que será el primero?

 

- [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en el objetivo 4 para poder programar la lógica de negocio?

2023-11-14 11:41 UTC, JJ requested changes
Gracias por enviar esto a corregir, pero todavía queda un pequeño camino por recorrer. El principal problema es que no se han seguido las buenas prácticas en lso mensajes de commit; no se ha aplicado la metodología de DDD con lo que es muy complicado saber dónde está realmente el modelo. Para que un modelo esté completo debe incluir todo lo necesario para la lógica de negocio, es decir, ponerse en los zapatos de @PabloBarTo en el objetivo 4 y ver si tenemos todo.

Cada jornada, el jugador tiene que
* Tomar el equipo que tiene, con una serie de jugadores y un presupuesto determinado. Asumo que es `Equipo`. 
* Tiene que mirar si quiere fichar a algún jugador. Imagino que eso es `Mercado`, pero ¿los jugadores están a la vez en `Mercado` y en `Equipo`? ¿Para saber en qué equipo está el jugador tienes que ir de equipo en equipo?

Esto lo que indica es una serie de problemas en la modelización. Por ejemplo, en #9 se pide "información sobre un jugador", pero no se dice nada sobre las restricciones que pueda tener (sólo estar en un equipo, y forzosamente en un equipo (o no, no lo sé)) o cómo se va a acceder a él (¿por una lista en orden de precio descendente o puntuación descendente?)

En fin, que habría que darle una vuelta a los issues (sobre todo al #9), modificar el código siguiendo las mejores prácticas en mensajes de commit, y volver de nuevo a hacer esta lista de comprobación a ver si todo está correcto.

2023-11-14 11:41 UTC, JJ commented on src/models/equipo.ts
> +    getPresupuesto(): number {
Sólo hay que incluir lso getters y setters que sean estrictamente necesarios.

2023-11-14 11:41 UTC, JJ commented on src/models/jugador.ts
> +    getValoresMercado(): ValorMercado[] {
¿Por qué lo declaras privado si luego lo puedes ver con el getter? Una vez más, ni constructor ni getters (ni setters, por supuesto) a no ser que sean estrictamente necesarios.

2023-11-14 11:41 UTC, JJ commented on src/models/mercado.ts
> +  private readonly jugadores: Jugador[];
ESto es esencialmente un array. En clases con un solo atributo hay que plantearse su necesidad.

2023-11-14 11:41 UTC, JJ commented on src/models/jugador.ts
> +    jornada: string | number,
Una jornada será lo uno o lo otro, según lo defina uno.

2023-11-14 11:41 UTC, JJ commented on src/models/jugador.ts
> +interface ValorMercado {
Prácticamente todo este fichero (salvo lo borrado) está creado con este commit cc73c13
No sigue las mejores prácticas porque no explica ninguna de las decisiones tomadas. Tampoco añade información al código en si, y oculta cosas que se hacen: no sólo "añade modelo del jugador" sino que añade también "Desempeño" y "ValorMercado" que tiene una fecha.

En #9, por otro lado, se habla de "Jornada" mientras que aquí se habla de "fechas".  En cuanto a `ValorMercado`, ¿hace falta la fecha o simplemente que se almacene de forma secuencial? ¿Se va a recuperar el valor del jugador en una fecha o sólo los n últimos?

2023-11-14 12:06 UTC, JJ commented
@diagmatrix te recuerdo que tienes que hacer el PR en el fichero de `IV-`, como todos los objetivos.

2023-11-20 18:54 UTC, diagmatrix commented
@PabloBarTo , @JJ Listo para revisión. He modificado los issues #8 , #9  y #10 aparte de los cambios en el código. Soy consciente de que los primeros mensajes de commit no son correctos.

2023-11-20 19:41 UTC, PabloBarTo commented
Yo en general lo veo bien aunque creo que deberías resolver los comentarios que te ha puesto el profesor que simplemente es darle al botón de resolve conversation.

2023-11-20 19:42 UTC, PabloBarTo commented
- [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y evidencian comprensión de las historias de usuario? Si no es así, es mejor que se le transmita antes de que empiece a crear cualquier código erróneo.

 

- [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido su lista de comprobación?

 

- [ ] ¿El código creado es una modelización válida de las historias de usuario creadas por ti, y te sirve como base para programar la lógica de negocio?

 

- [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de programación que hayáis consensuado, tanto en identificadores, como nombres de ficheros, como disposición de los diferentes ficheros en el repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y aportan código para resolver el problema planteado en el mismo?

- [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo ha hecho y documentado en el repositorio?

 

- [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone correspondiente, que será el primero?

 

- [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en el objetivo 4 para poder programar la lógica de negocio?

2023-11-22 07:27 UTC, JJ approved these changes
En general, se han respetado las buenas prácticas y se han creado issues apropiados; el problema es que se ha cargado al jugador, que debería de ser un objeto valor, con muchos datos y con estado que debería gestionarse desde otra  entidad. Eso ya le toca a @PabloBarTo , y a estas alturas no voy a bloquear la aprobación, así que adelante.

2023-11-22 07:28 UTC, JJ commented
Por favor @diagmatrix comienza con el 3 lo antes posible y entrégalo esta misma semana, si puede ser.

2023-12-22 12:03 UTC, merged